
CREATE TABLE [dbo].[tblCustomerStatus] (
  [CustomerStatus_Id] INT NOT NULL IDENTITY(0,1),
  [Description] VARCHAR(24) NULL ,
  CONSTRAINT [PK_tblCustomerStatus] PRIMARY KEY CLUSTERED 
  (
	[CustomerStatus_Id] ASC
  )WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO