
CREATE TABLE [dbo].[tblMediaItemPricing] (
  [MediaItemPricing_Id] INT NOT NULL IDENTITY(0,1),
  [Description] VARCHAR(16) NULL,
  [Price] DECIMAL(2) NULL,
 CONSTRAINT [PK_tblMediaItemPricing] PRIMARY KEY CLUSTERED 
(
	[MediaItemPricing_Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO