#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adv.SoloProject.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DBNovak")]
	public partial class MediaVaultDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttblCustomer(tblCustomer instance);
    partial void UpdatetblCustomer(tblCustomer instance);
    partial void DeletetblCustomer(tblCustomer instance);
    partial void InserttblMedia(tblMedia instance);
    partial void UpdatetblMedia(tblMedia instance);
    partial void DeletetblMedia(tblMedia instance);
    partial void InserttblFormat(tblFormat instance);
    partial void UpdatetblFormat(tblFormat instance);
    partial void DeletetblFormat(tblFormat instance);
    partial void InserttblMediaItem(tblMediaItem instance);
    partial void UpdatetblMediaItem(tblMediaItem instance);
    partial void DeletetblMediaItem(tblMediaItem instance);
    partial void InserttblMediaItemPricing(tblMediaItemPricing instance);
    partial void UpdatetblMediaItemPricing(tblMediaItemPricing instance);
    partial void DeletetblMediaItemPricing(tblMediaItemPricing instance);
    partial void InserttblStateCode(tblStateCode instance);
    partial void UpdatetblStateCode(tblStateCode instance);
    partial void DeletetblStateCode(tblStateCode instance);
    partial void InserttblPaymentType(tblPaymentType instance);
    partial void UpdatetblPaymentType(tblPaymentType instance);
    partial void DeletetblPaymentType(tblPaymentType instance);
    partial void InserttblCreditCardType(tblCreditCardType instance);
    partial void UpdatetblCreditCardType(tblCreditCardType instance);
    partial void DeletetblCreditCardType(tblCreditCardType instance);
    partial void InserttblCreditCard(tblCreditCard instance);
    partial void UpdatetblCreditCard(tblCreditCard instance);
    partial void DeletetblCreditCard(tblCreditCard instance);
    partial void InserttblRental(tblRental instance);
    partial void UpdatetblRental(tblRental instance);
    partial void DeletetblRental(tblRental instance);
    partial void InserttblRentalItem(tblRentalItem instance);
    partial void UpdatetblRentalItem(tblRentalItem instance);
    partial void DeletetblRentalItem(tblRentalItem instance);
    #endregion
		
		public MediaVaultDataContext() : 
				base(global::Adv.SoloProject.Data.Properties.Settings.Default.DBNovakConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MediaVaultDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MediaVaultDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MediaVaultDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MediaVaultDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblCustomer> tblCustomers
		{
			get
			{
				return this.GetTable<tblCustomer>();
			}
		}
		
		public System.Data.Linq.Table<tblMedia> tblMedias
		{
			get
			{
				return this.GetTable<tblMedia>();
			}
		}
		
		public System.Data.Linq.Table<tblFormat> tblFormats
		{
			get
			{
				return this.GetTable<tblFormat>();
			}
		}
		
		public System.Data.Linq.Table<tblMediaItem> tblMediaItems
		{
			get
			{
				return this.GetTable<tblMediaItem>();
			}
		}
		
		public System.Data.Linq.Table<tblMediaItemPricing> tblMediaItemPricings
		{
			get
			{
				return this.GetTable<tblMediaItemPricing>();
			}
		}
		
		public System.Data.Linq.Table<tblStateCode> tblStateCodes
		{
			get
			{
				return this.GetTable<tblStateCode>();
			}
		}
		
		public System.Data.Linq.Table<tblPaymentType> tblPaymentTypes
		{
			get
			{
				return this.GetTable<tblPaymentType>();
			}
		}
		
		public System.Data.Linq.Table<tblCreditCardType> tblCreditCardTypes
		{
			get
			{
				return this.GetTable<tblCreditCardType>();
			}
		}
		
		public System.Data.Linq.Table<tblCreditCard> tblCreditCards
		{
			get
			{
				return this.GetTable<tblCreditCard>();
			}
		}
		
		public System.Data.Linq.Table<tblRental> tblRentals
		{
			get
			{
				return this.GetTable<tblRental>();
			}
		}
		
		public System.Data.Linq.Table<tblRentalItem> tblRentalItems
		{
			get
			{
				return this.GetTable<tblRentalItem>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_GetMediaItemDisplay")]
		public ISingleResult<SP_GetMediaItemDisplayResult> SP_GetMediaItemDisplay()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_GetMediaItemDisplayResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblCustomer")]
	public partial class tblCustomer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Customer_Id;
		
		private string _AccountNumber;
		
		private string _FirstName;
		
		private string _LastName;
		
		private string _Address;
		
		private string _City;
		
		private string _State;
		
		private string _Zip;
		
		private string _Phone;
		
		private string _Email;
		
		private System.Nullable<System.DateTime> _DateOfBirth;
		
		private int _CustomerStatus_Id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCustomer_IdChanging(int value);
    partial void OnCustomer_IdChanged();
    partial void OnAccountNumberChanging(string value);
    partial void OnAccountNumberChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnStateChanging(string value);
    partial void OnStateChanged();
    partial void OnZipChanging(string value);
    partial void OnZipChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnDateOfBirthChanging(System.Nullable<System.DateTime> value);
    partial void OnDateOfBirthChanged();
    partial void OnCustomerStatus_IdChanging(int value);
    partial void OnCustomerStatus_IdChanged();
    #endregion
		
		public tblCustomer()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Customer_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Customer_Id
		{
			get
			{
				return this._Customer_Id;
			}
			set
			{
				if ((this._Customer_Id != value))
				{
					this.OnCustomer_IdChanging(value);
					this.SendPropertyChanging();
					this._Customer_Id = value;
					this.SendPropertyChanged("Customer_Id");
					this.OnCustomer_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountNumber", DbType="VarChar(64) NOT NULL", CanBeNull=false)]
		public string AccountNumber
		{
			get
			{
				return this._AccountNumber;
			}
			set
			{
				if ((this._AccountNumber != value))
				{
					this.OnAccountNumberChanging(value);
					this.SendPropertyChanging();
					this._AccountNumber = value;
					this.SendPropertyChanged("AccountNumber");
					this.OnAccountNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="VarChar(32)")]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="VarChar(32)")]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(48)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(24)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="VarChar(2)")]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this.OnStateChanging(value);
					this.SendPropertyChanging();
					this._State = value;
					this.SendPropertyChanged("State");
					this.OnStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zip", DbType="VarChar(9)")]
		public string Zip
		{
			get
			{
				return this._Zip;
			}
			set
			{
				if ((this._Zip != value))
				{
					this.OnZipChanging(value);
					this.SendPropertyChanging();
					this._Zip = value;
					this.SendPropertyChanged("Zip");
					this.OnZipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="VarChar(10)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(64)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateOfBirth", DbType="Date")]
		public System.Nullable<System.DateTime> DateOfBirth
		{
			get
			{
				return this._DateOfBirth;
			}
			set
			{
				if ((this._DateOfBirth != value))
				{
					this.OnDateOfBirthChanging(value);
					this.SendPropertyChanging();
					this._DateOfBirth = value;
					this.SendPropertyChanged("DateOfBirth");
					this.OnDateOfBirthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerStatus_Id", DbType="Int NOT NULL")]
		public int CustomerStatus_Id
		{
			get
			{
				return this._CustomerStatus_Id;
			}
			set
			{
				if ((this._CustomerStatus_Id != value))
				{
					this.OnCustomerStatus_IdChanging(value);
					this.SendPropertyChanging();
					this._CustomerStatus_Id = value;
					this.SendPropertyChanged("CustomerStatus_Id");
					this.OnCustomerStatus_IdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblMedia")]
	public partial class tblMedia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Media_Id;
		
		private System.Nullable<System.DateTime> _ReleaseDate;
		
		private string _Title;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMedia_IdChanging(int value);
    partial void OnMedia_IdChanged();
    partial void OnReleaseDateChanging(System.Nullable<System.DateTime> value);
    partial void OnReleaseDateChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    #endregion
		
		public tblMedia()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Media_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Media_Id
		{
			get
			{
				return this._Media_Id;
			}
			set
			{
				if ((this._Media_Id != value))
				{
					this.OnMedia_IdChanging(value);
					this.SendPropertyChanging();
					this._Media_Id = value;
					this.SendPropertyChanged("Media_Id");
					this.OnMedia_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReleaseDate", DbType="Date")]
		public System.Nullable<System.DateTime> ReleaseDate
		{
			get
			{
				return this._ReleaseDate;
			}
			set
			{
				if ((this._ReleaseDate != value))
				{
					this.OnReleaseDateChanging(value);
					this.SendPropertyChanging();
					this._ReleaseDate = value;
					this.SendPropertyChanged("ReleaseDate");
					this.OnReleaseDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="VarChar(64)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblFormat")]
	public partial class tblFormat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Format_Id;
		
		private string _Description;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFormat_IdChanging(int value);
    partial void OnFormat_IdChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    #endregion
		
		public tblFormat()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Format_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Format_Id
		{
			get
			{
				return this._Format_Id;
			}
			set
			{
				if ((this._Format_Id != value))
				{
					this.OnFormat_IdChanging(value);
					this.SendPropertyChanging();
					this._Format_Id = value;
					this.SendPropertyChanged("Format_Id");
					this.OnFormat_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(16)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblMediaItem")]
	public partial class tblMediaItem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MediaItem_Id;
		
		private System.Nullable<System.DateTime> _InvetoryDate;
		
		private int _Media_Id;
		
		private int _MediaItemState_Id;
		
		private int _MediaItemPricing_Id;
		
		private int _Format_Id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMediaItem_IdChanging(int value);
    partial void OnMediaItem_IdChanged();
    partial void OnInvetoryDateChanging(System.Nullable<System.DateTime> value);
    partial void OnInvetoryDateChanged();
    partial void OnMedia_IdChanging(int value);
    partial void OnMedia_IdChanged();
    partial void OnMediaItemState_IdChanging(int value);
    partial void OnMediaItemState_IdChanged();
    partial void OnMediaItemPricing_IdChanging(int value);
    partial void OnMediaItemPricing_IdChanged();
    partial void OnFormat_IdChanging(int value);
    partial void OnFormat_IdChanged();
    #endregion
		
		public tblMediaItem()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MediaItem_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MediaItem_Id
		{
			get
			{
				return this._MediaItem_Id;
			}
			set
			{
				if ((this._MediaItem_Id != value))
				{
					this.OnMediaItem_IdChanging(value);
					this.SendPropertyChanging();
					this._MediaItem_Id = value;
					this.SendPropertyChanged("MediaItem_Id");
					this.OnMediaItem_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvetoryDate", DbType="Date")]
		public System.Nullable<System.DateTime> InvetoryDate
		{
			get
			{
				return this._InvetoryDate;
			}
			set
			{
				if ((this._InvetoryDate != value))
				{
					this.OnInvetoryDateChanging(value);
					this.SendPropertyChanging();
					this._InvetoryDate = value;
					this.SendPropertyChanged("InvetoryDate");
					this.OnInvetoryDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Media_Id", DbType="Int NOT NULL")]
		public int Media_Id
		{
			get
			{
				return this._Media_Id;
			}
			set
			{
				if ((this._Media_Id != value))
				{
					this.OnMedia_IdChanging(value);
					this.SendPropertyChanging();
					this._Media_Id = value;
					this.SendPropertyChanged("Media_Id");
					this.OnMedia_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MediaItemState_Id", DbType="Int NOT NULL")]
		public int MediaItemState_Id
		{
			get
			{
				return this._MediaItemState_Id;
			}
			set
			{
				if ((this._MediaItemState_Id != value))
				{
					this.OnMediaItemState_IdChanging(value);
					this.SendPropertyChanging();
					this._MediaItemState_Id = value;
					this.SendPropertyChanged("MediaItemState_Id");
					this.OnMediaItemState_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MediaItemPricing_Id", DbType="Int NOT NULL")]
		public int MediaItemPricing_Id
		{
			get
			{
				return this._MediaItemPricing_Id;
			}
			set
			{
				if ((this._MediaItemPricing_Id != value))
				{
					this.OnMediaItemPricing_IdChanging(value);
					this.SendPropertyChanging();
					this._MediaItemPricing_Id = value;
					this.SendPropertyChanged("MediaItemPricing_Id");
					this.OnMediaItemPricing_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Format_Id", DbType="Int NOT NULL")]
		public int Format_Id
		{
			get
			{
				return this._Format_Id;
			}
			set
			{
				if ((this._Format_Id != value))
				{
					this.OnFormat_IdChanging(value);
					this.SendPropertyChanging();
					this._Format_Id = value;
					this.SendPropertyChanged("Format_Id");
					this.OnFormat_IdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblMediaItemPricing")]
	public partial class tblMediaItemPricing : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MediaItemPricing_Id;
		
		private string _Description;
		
		private decimal _Price;
		
		private int _Length;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMediaItemPricing_IdChanging(int value);
    partial void OnMediaItemPricing_IdChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnPriceChanging(decimal value);
    partial void OnPriceChanged();
    partial void OnLengthChanging(int value);
    partial void OnLengthChanged();
    #endregion
		
		public tblMediaItemPricing()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MediaItemPricing_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MediaItemPricing_Id
		{
			get
			{
				return this._MediaItemPricing_Id;
			}
			set
			{
				if ((this._MediaItemPricing_Id != value))
				{
					this.OnMediaItemPricing_IdChanging(value);
					this.SendPropertyChanging();
					this._MediaItemPricing_Id = value;
					this.SendPropertyChanged("MediaItemPricing_Id");
					this.OnMediaItemPricing_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(16) NOT NULL", CanBeNull=false)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Decimal(8,2) NOT NULL")]
		public decimal Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Length", DbType="Int NOT NULL")]
		public int Length
		{
			get
			{
				return this._Length;
			}
			set
			{
				if ((this._Length != value))
				{
					this.OnLengthChanging(value);
					this.SendPropertyChanging();
					this._Length = value;
					this.SendPropertyChanged("Length");
					this.OnLengthChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblStateCodes")]
	public partial class tblStateCode : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _State_Id;
		
		private string _Code;
		
		private string _Description;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnState_IdChanging(int value);
    partial void OnState_IdChanged();
    partial void OnCodeChanging(string value);
    partial void OnCodeChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    #endregion
		
		public tblStateCode()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int State_Id
		{
			get
			{
				return this._State_Id;
			}
			set
			{
				if ((this._State_Id != value))
				{
					this.OnState_IdChanging(value);
					this.SendPropertyChanging();
					this._State_Id = value;
					this.SendPropertyChanged("State_Id");
					this.OnState_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="VarChar(2)")]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(32)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblPaymentType")]
	public partial class tblPaymentType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PaymentType_Id;
		
		private string _Description;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPaymentType_IdChanging(int value);
    partial void OnPaymentType_IdChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    #endregion
		
		public tblPaymentType()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentType_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PaymentType_Id
		{
			get
			{
				return this._PaymentType_Id;
			}
			set
			{
				if ((this._PaymentType_Id != value))
				{
					this.OnPaymentType_IdChanging(value);
					this.SendPropertyChanging();
					this._PaymentType_Id = value;
					this.SendPropertyChanged("PaymentType_Id");
					this.OnPaymentType_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(16)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblCreditCardType")]
	public partial class tblCreditCardType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CreditCardType_Id;
		
		private string _Description;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCreditCardType_IdChanging(int value);
    partial void OnCreditCardType_IdChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    #endregion
		
		public tblCreditCardType()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreditCardType_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CreditCardType_Id
		{
			get
			{
				return this._CreditCardType_Id;
			}
			set
			{
				if ((this._CreditCardType_Id != value))
				{
					this.OnCreditCardType_IdChanging(value);
					this.SendPropertyChanging();
					this._CreditCardType_Id = value;
					this.SendPropertyChanged("CreditCardType_Id");
					this.OnCreditCardType_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(16)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblCreditCard")]
	public partial class tblCreditCard : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CreditCard_Id;
		
		private int _Customer_Id;
		
		private string _CardName;
		
		private string _CardNumber;
		
		private System.DateTime _CardExpiration;
		
		private int _CreditCardType_Id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCreditCard_IdChanging(int value);
    partial void OnCreditCard_IdChanged();
    partial void OnCustomer_IdChanging(int value);
    partial void OnCustomer_IdChanged();
    partial void OnCardNameChanging(string value);
    partial void OnCardNameChanged();
    partial void OnCardNumberChanging(string value);
    partial void OnCardNumberChanged();
    partial void OnCardExpirationChanging(System.DateTime value);
    partial void OnCardExpirationChanged();
    partial void OnCreditCardType_IdChanging(int value);
    partial void OnCreditCardType_IdChanged();
    #endregion
		
		public tblCreditCard()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreditCard_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CreditCard_Id
		{
			get
			{
				return this._CreditCard_Id;
			}
			set
			{
				if ((this._CreditCard_Id != value))
				{
					this.OnCreditCard_IdChanging(value);
					this.SendPropertyChanging();
					this._CreditCard_Id = value;
					this.SendPropertyChanged("CreditCard_Id");
					this.OnCreditCard_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Customer_Id", DbType="Int NOT NULL")]
		public int Customer_Id
		{
			get
			{
				return this._Customer_Id;
			}
			set
			{
				if ((this._Customer_Id != value))
				{
					this.OnCustomer_IdChanging(value);
					this.SendPropertyChanging();
					this._Customer_Id = value;
					this.SendPropertyChanged("Customer_Id");
					this.OnCustomer_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CardName", DbType="VarChar(48) NOT NULL", CanBeNull=false)]
		public string CardName
		{
			get
			{
				return this._CardName;
			}
			set
			{
				if ((this._CardName != value))
				{
					this.OnCardNameChanging(value);
					this.SendPropertyChanging();
					this._CardName = value;
					this.SendPropertyChanged("CardName");
					this.OnCardNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CardNumber", DbType="VarChar(19) NOT NULL", CanBeNull=false)]
		public string CardNumber
		{
			get
			{
				return this._CardNumber;
			}
			set
			{
				if ((this._CardNumber != value))
				{
					this.OnCardNumberChanging(value);
					this.SendPropertyChanging();
					this._CardNumber = value;
					this.SendPropertyChanged("CardNumber");
					this.OnCardNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CardExpiration", DbType="Date NOT NULL")]
		public System.DateTime CardExpiration
		{
			get
			{
				return this._CardExpiration;
			}
			set
			{
				if ((this._CardExpiration != value))
				{
					this.OnCardExpirationChanging(value);
					this.SendPropertyChanging();
					this._CardExpiration = value;
					this.SendPropertyChanged("CardExpiration");
					this.OnCardExpirationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreditCardType_Id", DbType="Int NOT NULL")]
		public int CreditCardType_Id
		{
			get
			{
				return this._CreditCardType_Id;
			}
			set
			{
				if ((this._CreditCardType_Id != value))
				{
					this.OnCreditCardType_IdChanging(value);
					this.SendPropertyChanging();
					this._CreditCardType_Id = value;
					this.SendPropertyChanged("CreditCardType_Id");
					this.OnCreditCardType_IdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblRental")]
	public partial class tblRental : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Rental_Id;
		
		private int _Customer_Id;
		
		private int _PaymentType_Id;
		
		private System.Nullable<System.DateTime> _CreditCard_Id__INT_NULL_______TransactionDate;
		
		private System.Nullable<decimal> _TransactionAmount;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRental_IdChanging(int value);
    partial void OnRental_IdChanged();
    partial void OnCustomer_IdChanging(int value);
    partial void OnCustomer_IdChanged();
    partial void OnPaymentType_IdChanging(int value);
    partial void OnPaymentType_IdChanged();
    partial void OnCreditCard_Id__INT_NULL_______TransactionDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreditCard_Id__INT_NULL_______TransactionDateChanged();
    partial void OnTransactionAmountChanging(System.Nullable<decimal> value);
    partial void OnTransactionAmountChanged();
    #endregion
		
		public tblRental()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rental_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Rental_Id
		{
			get
			{
				return this._Rental_Id;
			}
			set
			{
				if ((this._Rental_Id != value))
				{
					this.OnRental_IdChanging(value);
					this.SendPropertyChanging();
					this._Rental_Id = value;
					this.SendPropertyChanged("Rental_Id");
					this.OnRental_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Customer_Id", DbType="Int NOT NULL")]
		public int Customer_Id
		{
			get
			{
				return this._Customer_Id;
			}
			set
			{
				if ((this._Customer_Id != value))
				{
					this.OnCustomer_IdChanging(value);
					this.SendPropertyChanging();
					this._Customer_Id = value;
					this.SendPropertyChanged("Customer_Id");
					this.OnCustomer_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentType_Id", DbType="Int NOT NULL")]
		public int PaymentType_Id
		{
			get
			{
				return this._PaymentType_Id;
			}
			set
			{
				if ((this._PaymentType_Id != value))
				{
					this.OnPaymentType_IdChanging(value);
					this.SendPropertyChanging();
					this._PaymentType_Id = value;
					this.SendPropertyChanged("PaymentType_Id");
					this.OnPaymentType_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[CreditCard_Id` INT NULL ,\r\n  [TransactionDate]", Storage="_CreditCard_Id__INT_NULL_______TransactionDate", DbType="Date")]
		public System.Nullable<System.DateTime> CreditCard_Id__INT_NULL_______TransactionDate
		{
			get
			{
				return this._CreditCard_Id__INT_NULL_______TransactionDate;
			}
			set
			{
				if ((this._CreditCard_Id__INT_NULL_______TransactionDate != value))
				{
					this.OnCreditCard_Id__INT_NULL_______TransactionDateChanging(value);
					this.SendPropertyChanging();
					this._CreditCard_Id__INT_NULL_______TransactionDate = value;
					this.SendPropertyChanged("CreditCard_Id__INT_NULL_______TransactionDate");
					this.OnCreditCard_Id__INT_NULL_______TransactionDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransactionAmount", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> TransactionAmount
		{
			get
			{
				return this._TransactionAmount;
			}
			set
			{
				if ((this._TransactionAmount != value))
				{
					this.OnTransactionAmountChanging(value);
					this.SendPropertyChanging();
					this._TransactionAmount = value;
					this.SendPropertyChanged("TransactionAmount");
					this.OnTransactionAmountChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblRentalItem")]
	public partial class tblRentalItem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RentalItem_Id;
		
		private int _Rental_Id;
		
		private int _MediaItem_Id;
		
		private System.Nullable<System.DateTime> _DueDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRentalItem_IdChanging(int value);
    partial void OnRentalItem_IdChanged();
    partial void OnRental_IdChanging(int value);
    partial void OnRental_IdChanged();
    partial void OnMediaItem_IdChanging(int value);
    partial void OnMediaItem_IdChanged();
    partial void OnDueDateChanging(System.Nullable<System.DateTime> value);
    partial void OnDueDateChanged();
    #endregion
		
		public tblRentalItem()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RentalItem_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int RentalItem_Id
		{
			get
			{
				return this._RentalItem_Id;
			}
			set
			{
				if ((this._RentalItem_Id != value))
				{
					this.OnRentalItem_IdChanging(value);
					this.SendPropertyChanging();
					this._RentalItem_Id = value;
					this.SendPropertyChanged("RentalItem_Id");
					this.OnRentalItem_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rental_Id", DbType="Int NOT NULL")]
		public int Rental_Id
		{
			get
			{
				return this._Rental_Id;
			}
			set
			{
				if ((this._Rental_Id != value))
				{
					this.OnRental_IdChanging(value);
					this.SendPropertyChanging();
					this._Rental_Id = value;
					this.SendPropertyChanged("Rental_Id");
					this.OnRental_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MediaItem_Id", DbType="Int NOT NULL")]
		public int MediaItem_Id
		{
			get
			{
				return this._MediaItem_Id;
			}
			set
			{
				if ((this._MediaItem_Id != value))
				{
					this.OnMediaItem_IdChanging(value);
					this.SendPropertyChanging();
					this._MediaItem_Id = value;
					this.SendPropertyChanged("MediaItem_Id");
					this.OnMediaItem_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DueDate", DbType="Date")]
		public System.Nullable<System.DateTime> DueDate
		{
			get
			{
				return this._DueDate;
			}
			set
			{
				if ((this._DueDate != value))
				{
					this.OnDueDateChanging(value);
					this.SendPropertyChanging();
					this._DueDate = value;
					this.SendPropertyChanged("DueDate");
					this.OnDueDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class SP_GetMediaItemDisplayResult
	{
		
		private int _MediaItem_Id;
		
		private int _MediaItemPricing_Id;
		
		private string _Barcode;
		
		private string _Title;
		
		private System.Nullable<System.DateTime> _ReleaseDate;
		
		private string _Format;
		
		private System.Nullable<System.DateTime> _InvetoryDate;
		
		private string _Inventory;
		
		private string _Pricing;
		
		private decimal _Price;
		
		private int _Length;
		
		public SP_GetMediaItemDisplayResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MediaItem_Id", DbType="Int NOT NULL")]
		public int MediaItem_Id
		{
			get
			{
				return this._MediaItem_Id;
			}
			set
			{
				if ((this._MediaItem_Id != value))
				{
					this._MediaItem_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MediaItemPricing_Id", DbType="Int NOT NULL")]
		public int MediaItemPricing_Id
		{
			get
			{
				return this._MediaItemPricing_Id;
			}
			set
			{
				if ((this._MediaItemPricing_Id != value))
				{
					this._MediaItemPricing_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Barcode", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Barcode
		{
			get
			{
				return this._Barcode;
			}
			set
			{
				if ((this._Barcode != value))
				{
					this._Barcode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="VarChar(64)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReleaseDate", DbType="Date")]
		public System.Nullable<System.DateTime> ReleaseDate
		{
			get
			{
				return this._ReleaseDate;
			}
			set
			{
				if ((this._ReleaseDate != value))
				{
					this._ReleaseDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Format", DbType="VarChar(16)")]
		public string Format
		{
			get
			{
				return this._Format;
			}
			set
			{
				if ((this._Format != value))
				{
					this._Format = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvetoryDate", DbType="Date")]
		public System.Nullable<System.DateTime> InvetoryDate
		{
			get
			{
				return this._InvetoryDate;
			}
			set
			{
				if ((this._InvetoryDate != value))
				{
					this._InvetoryDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Inventory", DbType="VarChar(16)")]
		public string Inventory
		{
			get
			{
				return this._Inventory;
			}
			set
			{
				if ((this._Inventory != value))
				{
					this._Inventory = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pricing", DbType="VarChar(16) NOT NULL", CanBeNull=false)]
		public string Pricing
		{
			get
			{
				return this._Pricing;
			}
			set
			{
				if ((this._Pricing != value))
				{
					this._Pricing = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Decimal(8,2) NOT NULL")]
		public decimal Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this._Price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Length", DbType="Int NOT NULL")]
		public int Length
		{
			get
			{
				return this._Length;
			}
			set
			{
				if ((this._Length != value))
				{
					this._Length = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
